export interface CashflowStats {
  totalIncome: number;
  pendingPaymentAmount: number;
  totalExpense: number;
  netProfit: number;
  totalOrdersCount: number;
  activeOrdersCount: number;
  readyOrdersCount: number;
  completedOrdersCount: number;
  cancelledOrdersCount?: number;
}

export type OrderStatus =
  | "process"
  | "ready"
  | "completed"
  | "cancelled"
  | "pending"
  | "washing"
  | "drying_ironing";
export type PaymentStatus = "paid" | "unpaid";

export interface OrderItem {
  id: string;
  serviceType: string;
  weightOrQty: number;
  unit: string;
  pricePerUnit: number;
  subtotal: number;
  notes?: string;
}

export interface Order {
  id: string;
  tenantId: string;
  customerId?: string;
  invoiceNo: string;
  serviceType: string;
  weightOrQty: number;
  unit: string;
  pricePerUnit: number;
  totalAmount: number;
  items?: OrderItem[];
  status: OrderStatus;
  paymentStatus: PaymentStatus;
  paymentMethod: string;
  notes?: string;
  createdAt: string;
  estimatedCompletionAt?: string | null;
  completedAt?: string | null;
  customer?: { id: string; name: string; phone: string } | null;
  waSent?: boolean;
  waLogsCount?: number;
  latestWaLog?: WhatsAppLog | null;
}

export interface WhatsAppLog {
  id: string;
  tenantId: string;
  orderId?: string | null;
  recipientPhone: string;
  recipientName?: string | null;
  messagePreview?: string | null;
  status: "sent" | "failed" | "queued";
  mode: "baileys" | "manual";
  errorMessage?: string | null;
  createdAt: string;
}

export interface CashierShift {
  id: string;
  tenantId: string;
  userId: string;
  cashierName?: string;
  cashierEmail?: string;
  openedAt: string;
  closedAt?: string | null;
  startingCash: number;
  systemCashTotal: number;
  actualCashTotal?: number | null;
  discrepancy?: number | null;
  status: "open" | "closed";
  notes?: string | null;
  createdAt: string;
  expectedCash?: number;
  ordersCount?: number;
}

export interface Service {
  id: string;
  tenantId: string;
  name: string;
  unit: string;
  pricePerUnit: number;
  minOrder?: number;
  durationHours?: number;
  status: "active" | "inactive";
  createdAt?: string;
}

export interface Customer {
  id: string;
  tenantId?: string;
  name: string;
  phone: string;
  address?: string;
  notes?: string;
  createdAt?: string;
}

export interface Expense {
  id: string;
  tenantId?: string;
  type?: "income" | "expense";
  category: string;
  amount: number;
  notes: string;
  expenseDate: string;
  rentDurationMonths?: number | null;
  rentStartDate?: string | null;
  isAutoGenerated?: string | boolean;
  createdAt?: string;
}

export interface SopRatios {
  detergentMlPerKg: number;
  detergentPricePerLiter: number;
  perfumeMlPerKg: number;
  perfumePricePerLiter: number;
  gasCostPerKg: number;
  plasticCostPerKg: number;
}

export interface MaterialAuditItem {
  key: "detergent" | "perfume" | "gas" | "plastic";
  name: string;
  unitLabel: string;
  estimatedQty: number;
  estimatedCost: number;
  actualCost: number;
  differenceCost: number;
  ratioPct: number;
  status: "efficient" | "warning" | "danger" | "no_data";
  statusText: string;
}

export interface RentTrackingInfo {
  hasRent: boolean;
  totalPaid: number;
  durationMonths: number;
  monthlyAmortization: number;
  startDate: string | null;
  endDate: string | null;
  remainingMonths: number;
  isExpiringSoon: boolean;
}

export interface BusinessHealthAnalysis {
  healthScore: number;
  ratingText: string;
  ratingColor: "green" | "yellow" | "red";
  totalWashKg: number;
  totalRevenue: number;
  paidRevenue: number;
  unpaidRevenue: number;
  totalActualExpense: number;
  effectiveMonthlyExpense: number;
  netProfit: number;
  netMarginPct: number;
  chemicalExpenseTotal: number;
  chemicalRatioPct: number;
  materials: MaterialAuditItem[];
  rent: RentTrackingInfo;
  recommendations: string[];
  customExpenseCategories?: string[];
}

export interface LaundryService {
  id: string;
  name: string;
  unit: string;
  price: number;
}

export interface Tenant {
  id: string;
  userId?: string;
  outletName: string;
  phone: string;
  address: string;
  city?: string | null;
  status: "active" | "inactive";
  subscriptionUntil?: string | null;
  services?: LaundryService[];
  enableCashierShift?: string | boolean;
  owner?: { id: string; name: string; email: string; role: string } | null;
  totalOrders: number;
  totalOmset: number;
  bankName?: string | null;
  bankAccountNumber?: string | null;
  bankAccountName?: string | null;
  qrisInfo?: string | null;
  openingHours?: string | null;
  isTrial?: string | boolean;
  source?: string;
  referralCodeId?: string | null;
  acquiredAt?: string | null;
  customExpenseCategories?: string[] | string | null;
  customSopRatios?: string | null;
  tier?: AccountTier;
}

export type Role = "superadmin" | "tenant_owner" | "staff" | "marketing";

export interface User {
  id: string;
  name: string;
  email: string;
  role: Role;
  status: "active" | "inactive";
  subscriptionUntil?: string | null;
  createdAt: string;
  tenantId?: string | null;
  tenantName?: string | null;
  isTrial?: string | boolean;
  signupRequestId?: string | null;
  marketingUserId?: string | null;
  tutorialCompleted?: boolean | string;
  metadata?: string | null;
  tier?: AccountTier;
  isExpired?: boolean;
}

export type DateFilterPreset = "all" | "today" | "this_week" | "this_month" | "this_year";

export type TabType =
  | "overview"
  | "orders"
  | "cashflow"
  | "customers"
  | "services"
  | "reports"
  | "finance"
  | "tenants"
  | "users"
  | "settings"
  | "create-order"
  | "edit-order"
  | "logs"
  | "marketing"
  | "referral_codes"
  | "subscription"
  | "plans"
  | "signups"
  | "invoices"
  | "settings_platform"
  | "wa_numbers"
  | "ai";

// ==========================================
// Types: Referral & Marketing
// ==========================================

export interface ReferralCode {
  id: string;
  code: string;
  name: string;
  description?: string | null;
  discountType: "percent" | "fixed";
  discountValue: number;
  commissionType: "percent" | "fixed";
  commissionValue: number;
  maxUsage?: number | null;
  currentUsage: number;
  validFrom?: string | null;
  validUntil?: string | null;
  isActive: string | boolean;
  appliesToAllTenants: string | boolean;
  marketingProfileId?: string | null;
  createdByUserId?: string | null;
  createdAt: string;
  updatedAt?: string | null;
}

export interface MarketingProfile {
  id: string;
  userId: string;
  phone: string;
  bankName?: string | null;
  bankAccountNumber?: string | null;
  bankAccountName?: string | null;
  commissionRateDefault: number;
  totalEarned: number;
  totalWithdrawn: number;
  notes?: string | null;
  createdAt: string;
  userName?: string;
  userEmail?: string;
  userStatus?: string;
}

export interface MarketingCommission {
  id: string;
  marketingProfileId: string;
  referralCodeId: string;
  subscriptionInvoiceId?: string | null;
  tenantId?: string | null;
  baseAmount: number;
  commissionAmount: number;
  status: "pending" | "approved" | "paid" | "rejected";
  paidAt?: string | null;
  notes?: string | null;
  createdAt: string;
  codeName?: string;
  marketingName?: string;
}

export interface ReferralStats {
  code: string;
  currentUsage: number;
  maxUsage?: number | null;
  clicks: number;
  signups: number;
  conversionRate: number;
  paymentsCount: number;
  totalRevenue: number;
  totalCommission: number;
}

// ==========================================
// Types: Subscription, Plans & Settings
// ==========================================

export interface Plan {
  id: string;
  code: string;
  name: string;
  description?: string | null;
  durationMonths: number;
  pricePerMonth: number;
  features?: string[] | string;
  maxWaNumbers: number;
  maxStaff: number;
  aiTokenQuotaDaily: number;
  isTrialAllowed: string | boolean;
  isActive: string | boolean;
  sortOrder: number;
  createdAt?: string;
}

export interface PlatformSettings {
  id: string;
  platformName: string;
  platformLogo?: string | null;
  bankName?: string | null;
  bankAccountNumber?: string | null;
  bankAccountName?: string | null;
  qrisInfo?: string | null;
  defaultTrialDays: number;
  defaultAiDailyQuota: number;
  supportPhone?: string | null;
  supportEmail?: string | null;
  termsUrl?: string | null;
  privacyUrl?: string | null;
  updatedAt?: string;
}

export interface SignupRequest {
  id: string;
  outletName: string;
  ownerName: string;
  phone: string;
  email: string;
  city?: string | null;
  address?: string | null;
  referralCode?: string | null;
  referralCodeId?: string | null;
  planId?: string | null;
  status: "pending" | "activated" | "rejected";
  ipAddress?: string | null;
  userAgent?: string | null;
  createdTenantId?: string | null;
  createdUserId?: string | null;
  activatedAt?: string | null;
  notes?: string | null;
  createdAt: string;
}

export interface SubscriptionInvoice {
  id: string;
  invoiceNo: string;
  tenantId: string;
  userId: string;
  planId?: string | null;
  referralCodeId?: string | null;
  durationMonths: number;
  originalAmount: number;
  discountAmount: number;
  finalAmount: number;
  status: "unpaid" | "pending_verification" | "paid" | "rejected" | "cancelled";
  paymentProofUrl?: string | null;
  paymentProofUploadedAt?: string | null;
  verifiedByUserId?: string | null;
  verifiedAt?: string | null;
  rejectionReason?: string | null;
  periodStart?: string | null;
  periodEnd?: string | null;
  notes?: string | null;
  createdAt: string;
  outletName?: string;
  ownerName?: string;
  planName?: string;
}

export interface SubscriptionSummary {
  tenantId: string;
  outletName: string;
  isTrial: boolean;
  isActive: boolean;
  subscriptionUntil: string | null;
  daysRemaining: number;
  status: string;
  referralCodeUsed?: string | null;
  pendingInvoice?: SubscriptionInvoice | null;
  platformBank?: {
    bankName: string | null;
    bankAccountNumber: string | null;
    bankAccountName: string | null;
    qrisInfo: string | null;
  };
}

// ==========================================
// Types: Subscription Tiers & Feature Gating
// (Matt Pocock Strict Discriminated Architecture)
// ==========================================

export type AccountTier = "free" | "pro" | "premium";

export interface TierCapabilities {
  readonly canConnectThermalPrinter: boolean;
  readonly canManageEmployees: boolean;
  readonly canManageMultipleBranches: boolean;
  readonly maxBranches: number;
  readonly maxStaff: number;
  readonly isComingSoon: boolean;
}

export interface TierDefinition extends TierCapabilities {
  readonly id: AccountTier;
  readonly name: string;
  readonly badgeLabel: string;
  readonly description: string;
  readonly highlightFeature: string;
  readonly pricePerMonth: number;
}

export const ACCOUNT_TIERS = {
  free: {
    id: "free",
    name: "Free",
    badgeLabel: "Gratis",
    description: "Operasional dasar POS kasir & nota WhatsApp untuk 1 gerai laundry",
    highlightFeature: "1 Cabang • Tanpa Karyawan • Cetak Standar",
    pricePerMonth: 0,
    canConnectThermalPrinter: false,
    canManageEmployees: false,
    canManageMultipleBranches: false,
    maxBranches: 1,
    maxStaff: 0,
    isComingSoon: false,
  },
  pro: {
    id: "pro",
    name: "Pro",
    badgeLabel: "Pro (Trial 7 Hari)",
    description: "Paket lengkap dengan WhatsApp otomatis, laporan keuangan & asisten AI",
    highlightFeature: "1 Cabang • WhatsApp Otomatis • Laporan Laba Rugi",
    pricePerMonth: 60000,
    canConnectThermalPrinter: false, // Locked until Premium release
    canManageEmployees: false,      // Locked until Premium release
    canManageMultipleBranches: false, // Locked until Premium release
    maxBranches: 1,
    maxStaff: 0,
    isComingSoon: false,
  },
  premium: {
    id: "premium",
    name: "Premium",
    badgeLabel: "Premium",
    description: "Solusi enterprise multi-cabang, delegasi staf kasir & printer thermal bluetooth",
    highlightFeature: "Multi-Cabang • Kelola Karyawan • Printer Thermal POS",
    pricePerMonth: 100000,
    canConnectThermalPrinter: true,
    canManageEmployees: true,
    canManageMultipleBranches: true,
    maxBranches: 10,
    maxStaff: 25,
    isComingSoon: true, // Saat ini berstatus Coming Soon
  },
} as const satisfies Record<AccountTier, TierDefinition>;

export type PremiumFeatureKey =
  | "thermal_printer"
  | "employee_management"
  | "branch_management";

export interface PremiumFeatureMeta {
  readonly key: PremiumFeatureKey;
  readonly title: string;
  readonly subtitle: string;
  readonly badge: string;
  readonly capabilities: readonly string[];
  readonly releaseStatus: "coming_soon" | "in_development";
}

export const PREMIUM_FEATURES_REGISTRY = {
  thermal_printer: {
    key: "thermal_printer",
    title: "Koneksi Thermal Printer POS",
    subtitle: "Cetak nota kasir instan via Bluetooth / USB Thermal Printer (58mm / 80mm)",
    badge: "Paket Premium • Coming Soon",
    capabilities: [
      "Koneksi instan Web Bluetooth & USB Serial ke printer kasir",
      "Kustomisasi format header, footer, & QRIS pada struk kasir",
      "Cetak nota 1-klik langsung dari modal checkout pesanan kasir",
    ],
    releaseStatus: "coming_soon",
  },
  employee_management: {
    key: "employee_management",
    title: "Manajemen Karyawan & Kasir",
    subtitle: "Kelola akun staf kasir, shift kerja, dan pantau rekonsiliasi laci kas",
    badge: "Paket Premium • Coming Soon",
    capabilities: [
      "Tambah akun kasir/operator terisolasi dengan pembagian hak akses terukur",
      "Audit rekonsiliasi kas laci & log aktivitas per staf kasir",
      "Reset sandi dan pembekuan akun staf secara fleksibel",
    ],
    releaseStatus: "coming_soon",
  },
  branch_management: {
    key: "branch_management",
    title: "Manajemen Multi-Cabang Outlet",
    subtitle: "Kelola dan pantau seluruh cabang laundry dalam satu akun Owner terpadu",
    badge: "Paket Premium • Coming Soon",
    capabilities: [
      "Tambah dan kelola hingga 10 gerai/cabang dalam 1 akun Owner",
      "Pemisahan omzet, buku kas, dan laporan performa per gerai",
      "Peralihan cepat antar cabang tanpa perlu logout akun",
    ],
    releaseStatus: "coming_soon",
  },
} as const satisfies Record<PremiumFeatureKey, PremiumFeatureMeta>;

/**
 * Type guard / Feature permission checker.
 * Mengembalikan apakah tier tertentu diizinkan mengakses fitur premium tertentu.
 */
export function isFeatureAccessible(
  tier: AccountTier | undefined | null,
  feature: PremiumFeatureKey
): boolean {
  if (!tier) return false;
  const config = ACCOUNT_TIERS[tier];
  if (!config) return false;

  switch (feature) {
    case "thermal_printer":
      return config.canConnectThermalPrinter;
    case "employee_management":
      return config.canManageEmployees;
    case "branch_management":
      return config.canManageMultipleBranches;
    default: {
      const _exhaustiveCheck: never = feature;
      return _exhaustiveCheck;
    }
  }
}

